### ISSUE TITLE
Switching account

### ISSUE THREAD

**Issue by toniengelhardt** [toniengelhardt/merklin#20]
Ideally, later on, we would display data without actually connecting to a wallet, simply by adding one or more addresses (see Zapper bundles, etc.). For now it is better to require a wallet until we cache the network requests, etc.

**Comment by RyanPaulGannon** [comment]
Just something I noticed and didn't want to forget, there is a way we can use MetaMask on the mobile version as opposed to purely using the (e.g. Brave) browser wallet (which I've been doing). I'm going to have a look in to this, as I didn't realise it was possible.

**Comment by toniengelhardt** [comment]
It's possible via WalletConnect if you have the MetaMask app installed.

**Comment by RyanPaulGannon** [comment]
Brilliant, so it is!
